name: 'Manifest'
description: 'Manage Pull Requests that modify a west manifest'
inputs:
  github-token:
    description: 'The token to authenticate with'
  verbosity:
    required: false
    default: '0'
  manifest-path:
    description: 'The path to the manifest file'
    required: true
  messages:
    description: '|-separated Messages to post'
    required: false
    default: 'none'
  labels:
    description: 'Comma-separated list of labels. First one corresponds to the
                  one to apply only when PR revisions are present.'
    required: false
    default: 'none'
  label-prefix:
    description: 'Prefix for project-specific labels.'
    required: false
    default: 'none'

runs:
  using: "composite"
  steps: 
    - id: setup-python
      run: |
        pip3 install setuptools wheel
        pip3 install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - id: run-python
      run: |
           python3 ${{ github.action_path }}/action.py -p "${{ inputs.manifest-path }}" \
           -m "${{ inputs.messages }}" -l "${{ inputs.labels }}" --lp "${{ inputs.labels }}" \
           -v "{{ inputs.verbosity }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
